title: Hewwo!
author: Omega-Alpha-24
email: OmegaAlpha24@outlook.com
description: > Hi! Welcome to my first second lesson thing!
twitter_username: I do not have a twitter
github_username:  Omega-Alpha-24
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
